// ==========================================
// Arena Win Tracker - Data & Champion Roster
// ==========================================

const DEFAULT_DATA_DRAGON_VERSION = "15.4.1";
const STORAGE_KEY = "arena_wins_data_v2";
const SETTINGS_KEY = "arena_wins_settings_v2";
const COOKIE_LEGACY_KEY = "lol_champ_wins";

// Canonical list guarantees URL sharing backwards & forwards compatibility
const CANONICAL_FALLBACK_ROSTER = [
  { id: "Aatrox", name: "Aatrox", tags: ["Fighter", "Tank"], title: "the Darkin Blade" },
  { id: "Ahri", name: "Ahri", tags: ["Mage", "Assassin"], title: "the Nine-Tailed Fox" },
  { id: "Akali", name: "Akali", tags: ["Assassin"], title: "the Rogue Assassin" },
  { id: "Akshan", name: "Akshan", tags: ["Marksman", "Assassin"], title: "the Rogue Sentinel" },
  { id: "Alistar", name: "Alistar", tags: ["Tank", "Support"], title: "the Minotaur" },
  { id: "Ambessa", name: "Ambessa", tags: ["Fighter", "Assassin"], title: "Matriarch of War" },
  { id: "Amumu", name: "Amumu", tags: ["Tank", "Mage"], title: "the Sad Mummy" },
  { id: "Anivia", name: "Anivia", tags: ["Mage", "Support"], title: "the Cryophoenix" },
  { id: "Annie", name: "Annie", tags: ["Mage", "Support"], title: "the Dark Child" },
  { id: "Aphelios", name: "Aphelios", tags: ["Marksman"], title: "the Weapon of the Faithful" },
  { id: "Ashe", name: "Ashe", tags: ["Marksman", "Support"], title: "the Frost Archer" },
  { id: "AurelionSol", name: "Aurelion Sol", tags: ["Mage"], title: "The Star Forger" },
  { id: "Aurora", name: "Aurora", tags: ["Mage", "Assassin"], title: "the Witch Between Worlds" },
  { id: "Azir", name: "Azir", tags: ["Mage", "Marksman"], title: "the Emperor of the Sands" },
  { id: "Bard", name: "Bard", tags: ["Support", "Mage"], title: "the Wandering Caretaker" },
  { id: "Belveth", name: "Bel'Veth", tags: ["Fighter"], title: "the Empress of the Void" },
  { id: "Blitzcrank", name: "Blitzcrank", tags: ["Tank", "Support"], title: "the Great Steam Golem" },
  { id: "Brand", name: "Brand", tags: ["Mage", "Support"], title: "the Burning Vengeance" },
  { id: "Braum", name: "Braum", tags: ["Support", "Tank"], title: "the Heart of the Freljord" },
  { id: "Briar", name: "Briar", tags: ["Fighter", "Assassin"], title: "the Restrained Hunger" },
  { id: "Caitlyn", name: "Caitlyn", tags: ["Marksman"], title: "the Sheriff of Piltover" },
  { id: "Camille", name: "Camille", tags: ["Fighter", "Tank"], title: "the Steel Shadow" },
  { id: "Cassiopeia", name: "Cassiopeia", tags: ["Mage"], title: "the Serpent's Embrace" },
  { id: "Chogath", name: "Cho'Gath", tags: ["Tank", "Mage"], title: "the Terror of the Void" },
  { id: "Corki", name: "Corki", tags: ["Marksman", "Mage"], title: "the Daring Bombardier" },
  { id: "Darius", name: "Darius", tags: ["Fighter", "Tank"], title: "the Hand of Noxus" },
  { id: "Diana", name: "Diana", tags: ["Fighter", "Mage"], title: "Scorn of the Moon" },
  { id: "DrMundo", name: "Dr. Mundo", tags: ["Fighter", "Tank"], title: "the Madman of Zaun" },
  { id: "Draven", name: "Draven", tags: ["Marksman"], title: "the Glorious Executioner" },
  { id: "Ekko", name: "Ekko", tags: ["Assassin", "Mage"], title: "the Boy Who Shattered Time" },
  { id: "Elise", name: "Elise", tags: ["Mage", "Assassin"], title: "the Spider Queen" },
  { id: "Evelynn", name: "Evelynn", tags: ["Assassin", "Mage"], title: "Agony's Embrace" },
  { id: "Ezreal", name: "Ezreal", tags: ["Marksman", "Mage"], title: "the Prodigal Explorer" },
  { id: "Fiddlesticks", name: "Fiddlesticks", tags: ["Mage", "Support"], title: "the Ancient Fear" },
  { id: "Fiora", name: "Fiora", tags: ["Fighter", "Assassin"], title: "the Grand Duelist" },
  { id: "Fizz", name: "Fizz", tags: ["Assassin", "Fighter"], title: "the Tidal Trickster" },
  { id: "Galio", name: "Galio", tags: ["Tank", "Mage"], title: "the Colossus" },
  { id: "Gangplank", name: "Gangplank", tags: ["Fighter"], title: "the Saltwater Scourge" },
  { id: "Garen", name: "Garen", tags: ["Fighter", "Tank"], title: "The Might of Demacia" },
  { id: "Gnar", name: "Gnar", tags: ["Fighter", "Tank"], title: "the Missing Link" },
  { id: "Gragas", name: "Gragas", tags: ["Fighter", "Mage"], title: "the Rabble Rouser" },
  { id: "Graves", name: "Graves", tags: ["Marksman"], title: "the Outlaw" },
  { id: "Gwen", name: "Gwen", tags: ["Fighter", "Assassin"], title: "The Hallowed Seamstress" },
  { id: "Hecarim", name: "Hecarim", tags: ["Fighter", "Tank"], title: "the Shadow of War" },
  { id: "Heimerdinger", name: "Heimerdinger", tags: ["Mage", "Support"], title: "the Revered Inventor" },
  { id: "Hwei", name: "Hwei", tags: ["Mage", "Support"], title: "the Visionary" },
  { id: "Illaoi", name: "Illaoi", tags: ["Fighter", "Tank"], title: "the Kraken Priestess" },
  { id: "Irelia", name: "Irelia", tags: ["Fighter", "Assassin"], title: "the Blade Dancer" },
  { id: "Ivern", name: "Ivern", tags: ["Support", "Mage"], title: "the Green Father" },
  { id: "Janna", name: "Janna", tags: ["Support", "Mage"], title: "the Storm's Fury" },
  { id: "JarvanIV", name: "Jarvan IV", tags: ["Tank", "Fighter"], title: "the Exemplar of Demacia" },
  { id: "Jax", name: "Jax", tags: ["Fighter", "Assassin"], title: "Grandmaster at Arms" },
  { id: "Jayce", name: "Jayce", tags: ["Fighter", "Marksman"], title: "the Defender of Tomorrow" },
  { id: "Jhin", name: "Jhin", tags: ["Marksman", "Mage"], title: "the Virtuoso" },
  { id: "Jinx", name: "Jinx", tags: ["Marksman"], title: "the Loose Cannon" },
  { id: "KSante", name: "K'Sante", tags: ["Tank", "Fighter"], title: "the Pride of Nazumah" },
  { id: "Kaisa", name: "Kai'Sa", tags: ["Marksman", "Assassin"], title: "Daughter of the Void" },
  { id: "Kalista", name: "Kalista", tags: ["Marksman"], title: "the Spear of Vengeance" },
  { id: "Karma", name: "Karma", tags: ["Mage", "Support"], title: "the Enlightened One" },
  { id: "Karthus", name: "Karthus", tags: ["Mage"], title: "the Deathsinger" },
  { id: "Kassadin", name: "Kassadin", tags: ["Assassin", "Mage"], title: "the Void Walker" },
  { id: "Katarina", name: "Katarina", tags: ["Assassin", "Mage"], title: "the Sinister Blade" },
  { id: "Kayle", name: "Kayle", tags: ["Fighter", "Support"], title: "the Righteous" },
  { id: "Kayn", name: "Kayn", tags: ["Fighter", "Assassin"], title: "the Shadow Reaper" },
  { id: "Kennen", name: "Kennen", tags: ["Mage", "Marksman"], title: "the Heart of the Tempest" },
  { id: "Khazix", name: "Kha'Zix", tags: ["Assassin"], title: "the Voidreaver" },
  { id: "Kindred", name: "Kindred", tags: ["Marksman"], title: "The Eternal Hunters" },
  { id: "Kled", name: "Kled", tags: ["Fighter", "Tank"], title: "the Cantankerous Cavalier" },
  { id: "KogMaw", name: "Kog'Maw", tags: ["Marksman", "Mage"], title: "the Mouth of the Abyss" },
  { id: "Leblanc", name: "LeBlanc", tags: ["Assassin", "Mage"], title: "the Deceiver" },
  { id: "LeeSin", name: "Lee Sin", tags: ["Fighter", "Assassin"], title: "the Blind Monk" },
  { id: "Leona", name: "Leona", tags: ["Tank", "Support"], title: "the Radiant Dawn" },
  { id: "Lillia", name: "Lillia", tags: ["Fighter", "Mage"], title: "the Bashful Bloom" },
  { id: "Lissandra", name: "Lissandra", tags: ["Mage"], title: "the Ice Witch" },
  { id: "Lucian", name: "Lucian", tags: ["Marksman", "Assassin"], title: "the Purifier" },
  { id: "Lulu", name: "Lulu", tags: ["Support", "Mage"], title: "the Fae Sorceress" },
  { id: "Lux", name: "Lux", tags: ["Mage", "Support"], title: "the Lady of Luminosity" },
  { id: "Malphite", name: "Malphite", tags: ["Tank", "Fighter"], title: "Shard of the Monolith" },
  { id: "Malzahar", name: "Malzahar", tags: ["Mage", "Assassin"], title: "the Prophet of the Void" },
  { id: "Maokai", name: "Maokai", tags: ["Tank", "Mage"], title: "the Twisted Treant" },
  { id: "MasterYi", name: "Master Yi", tags: ["Assassin", "Fighter"], title: "the Wuju Bladesman" },
  { id: "Mel", name: "Mel", tags: ["Mage", "Support"], title: "the Medarda Heir" },
  { id: "Milio", name: "Milio", tags: ["Support", "Mage"], title: "the Gentle Flame" },
  { id: "MissFortune", name: "Miss Fortune", tags: ["Marksman", "Mage"], title: "the Bounty Hunter" },
  { id: "Mordekaiser", name: "Mordekaiser", tags: ["Fighter", "Mage"], title: "the Iron Revenant" },
  { id: "Morgana", name: "Morgana", tags: ["Mage", "Support"], title: "the Fallen" },
  { id: "Naafiri", name: "Naafiri", tags: ["Assassin", "Fighter"], title: "the Hound of a Hundred Bites" },
  { id: "Nami", name: "Nami", tags: ["Support", "Mage"], title: "the Tidecaller" },
  { id: "Nasus", name: "Nasus", tags: ["Fighter", "Tank"], title: "the Curator of the Sands" },
  { id: "Nautilus", name: "Nautilus", tags: ["Tank", "Support"], title: "the Titan of the Depths" },
  { id: "Neeko", name: "Neeko", tags: ["Mage", "Support"], title: "the Curious Chameleon" },
  { id: "Nidalee", name: "Nidalee", tags: ["Assassin", "Mage"], title: "the Bestial Huntress" },
  { id: "Nilah", name: "Nilah", tags: ["Fighter", "Assassin"], title: "the Joy Unbound" },
  { id: "Nocturne", name: "Nocturne", tags: ["Assassin", "Fighter"], title: "the Eternal Nightmare" },
  { id: "Nunu", name: "Nunu & Willump", tags: ["Tank", "Fighter"], title: "the Boy and His Yeti" },
  { id: "Olaf", name: "Olaf", tags: ["Fighter", "Tank"], title: "the Berserker" },
  { id: "Orianna", name: "Orianna", tags: ["Mage", "Support"], title: "the Lady of Clockwork" },
  { id: "Ornn", name: "Ornn", tags: ["Tank", "Fighter"], title: "The Fire below the Mountain" },
  { id: "Pantheon", name: "Pantheon", tags: ["Fighter", "Assassin"], title: "the Unbreakable Spear" },
  { id: "Poppy", name: "Poppy", tags: ["Tank", "Fighter"], title: "Keeper of the Hammer" },
  { id: "Pyke", name: "Pyke", tags: ["Support", "Assassin"], title: "the Bloodharbor Ripper" },
  { id: "Qiyana", name: "Qiyana", tags: ["Assassin", "Fighter"], title: "Empress of the Elements" },
  { id: "Quinn", name: "Quinn", tags: ["Marksman", "Assassin"], title: "Demacia's Wings" },
  { id: "Rakan", name: "Rakan", tags: ["Support"], title: "The Charmer" },
  { id: "Rammus", name: "Rammus", tags: ["Tank", "Fighter"], title: "the Armordillo" },
  { id: "RekSai", name: "Rek'Sai", tags: ["Fighter", "Assassin"], title: "the Void Burrower" },
  { id: "Rell", name: "Rell", tags: ["Tank", "Support"], title: "the Iron Maiden" },
  { id: "Renata", name: "Renata Glasc", tags: ["Support", "Mage"], title: "the Chem-Baroness" },
  { id: "Renekton", name: "Renekton", tags: ["Fighter", "Tank"], title: "the Butcher of the Sands" },
  { id: "Rengar", name: "Rengar", tags: ["Assassin", "Fighter"], title: "the Pridestalker" },
  { id: "Riven", name: "Riven", tags: ["Fighter", "Assassin"], title: "the Exile" },
  { id: "Rumble", name: "Rumble", tags: ["Fighter", "Mage"], title: "the Mechanized Menace" },
  { id: "Ryze", name: "Ryze", tags: ["Mage", "Fighter"], title: "the Rune Mage" },
  { id: "Samira", name: "Samira", tags: ["Marksman", "Assassin"], title: "the Desert Rose" },
  { id: "Sejuani", name: "Sejuani", tags: ["Tank", "Fighter"], title: "Fury of the North" },
  { id: "Senna", name: "Senna", tags: ["Marksman", "Support"], title: "the Redeemer" },
  { id: "Seraphine", name: "Seraphine", tags: ["Mage", "Support"], title: "the Starry-Eyed Songstress" },
  { id: "Sett", name: "Sett", tags: ["Fighter", "Tank"], title: "the Boss" },
  { id: "Shaco", name: "Shaco", tags: ["Assassin"], title: "the Demon Jester" },
  { id: "Shen", name: "Shen", tags: ["Tank", "Support"], title: "the Eye of Twilight" },
  { id: "Shyvana", name: "Shyvana", tags: ["Fighter", "Tank"], title: "the Half-Dragon" },
  { id: "Singed", name: "Singed", tags: ["Tank", "Fighter"], title: "the Mad Chemist" },
  { id: "Sion", name: "Sion", tags: ["Tank", "Fighter"], title: "The Undead Juggernaut" },
  { id: "Sivir", name: "Sivir", tags: ["Marksman"], title: "the Battle Mistress" },
  { id: "Skarner", name: "Skarner", tags: ["Tank", "Fighter"], title: "the Primordial Sovereign" },
  { id: "Smolder", name: "Smolder", tags: ["Marksman", "Mage"], title: "the Fiery Fledgling" },
  { id: "Sona", name: "Sona", tags: ["Support", "Mage"], title: "Maven of the Strings" },
  { id: "Soraka", name: "Soraka", tags: ["Support", "Mage"], title: "the Starchild" },
  { id: "Swain", name: "Swain", tags: ["Mage", "Fighter"], title: "the Noxian Grand General" },
  { id: "Sylas", name: "Sylas", tags: ["Mage", "Assassin"], title: "the Unshackled" },
  { id: "Syndra", name: "Syndra", tags: ["Mage"], title: "the Dark Sovereign" },
  { id: "TahmKench", name: "Tahm Kench", tags: ["Support", "Tank"], title: "The River King" },
  { id: "Taliyah", name: "Taliyah", tags: ["Mage", "Support"], title: "the Stoneweaver" },
  { id: "Talon", name: "Talon", tags: ["Assassin"], title: "the Blade's Shadow" },
  { id: "Taric", name: "Taric", tags: ["Support", "Tank"], title: "the Shield of Valoran" },
  { id: "Teemo", name: "Teemo", tags: ["Marksman", "Mage"], title: "the Swift Scout" },
  { id: "Thresh", name: "Thresh", tags: ["Support", "Tank"], title: "the Chain Warden" },
  { id: "Tristana", name: "Tristana", tags: ["Marksman", "Assassin"], title: "the Yordle Gunner" },
  { id: "Trundle", name: "Trundle", tags: ["Fighter", "Tank"], title: "the Troll King" },
  { id: "Tryndamere", name: "Tryndamere", tags: ["Fighter", "Assassin"], title: "the Barbarian King" },
  { id: "TwistedFate", name: "Twisted Fate", tags: ["Mage", "Marksman"], title: "the Card Master" },
  { id: "Twitch", name: "Twitch", tags: ["Marksman", "Assassin"], title: "the Plague Rat" },
  { id: "Udyr", name: "Udyr", tags: ["Fighter", "Tank"], title: "the Spirit Walker" },
  { id: "Urgot", name: "Urgot", tags: ["Fighter", "Tank"], title: "the Dreadnought" },
  { id: "Varus", name: "Varus", tags: ["Marksman", "Mage"], title: "the Arrow of Retribution" },
  { id: "Vayne", name: "Vayne", tags: ["Marksman", "Assassin"], title: "the Night Hunter" },
  { id: "Veigar", name: "Veigar", tags: ["Mage"], title: "the Tiny Master of Evil" },
  { id: "Velkoz", name: "Vel'Koz", tags: ["Mage", "Support"], title: "the Eye of the Void" },
  { id: "Vex", name: "Vex", tags: ["Mage"], title: "the Gloomist" },
  { id: "Vi", name: "Vi", tags: ["Fighter", "Assassin"], title: "the Piltover Enforcer" },
  { id: "Viego", name: "Viego", tags: ["Assassin", "Fighter"], title: "The Ruined King" },
  { id: "Viktor", name: "Viktor", tags: ["Mage"], title: "the Machine Herald" },
  { id: "Vladimir", name: "Vladimir", tags: ["Mage", "Tank"], title: "the Crimson Reaper" },
  { id: "Volibear", name: "Volibear", tags: ["Fighter", "Tank"], title: "the Relentless Storm" },
  { id: "Warwick", name: "Warwick", tags: ["Fighter", "Tank"], title: "the Uncaged Wrath of Zaun" },
  { id: "MonkeyKing", name: "Wukong", tags: ["Fighter", "Tank"], title: "the Monkey King" },
  { id: "Xayah", name: "Xayah", tags: ["Marksman"], title: "the Rebel" },
  { id: "Xerath", name: "Xerath", tags: ["Mage", "Support"], title: "the Magus Ascendant" },
  { id: "XinZhao", name: "Xin Zhao", tags: ["Fighter", "Assassin"], title: "the Seneschal of Demacia" },
  { id: "Yasuo", name: "Yasuo", tags: ["Fighter", "Assassin"], title: "the Unforgiven" },
  { id: "Yone", name: "Yone", tags: ["Assassin", "Fighter"], title: "the Unforgotten" },
  { id: "Yorick", name: "Yorick", tags: ["Fighter", "Tank"], title: "Shepherd of Souls" },
  { id: "Yuumi", name: "Yuumi", tags: ["Support", "Mage"], title: "the Magical Cat" },
  { id: "Zac", name: "Zac", tags: ["Tank", "Fighter"], title: "the Secret Weapon" },
  { id: "Zed", name: "Zed", tags: ["Assassin"], title: "the Master of Shadows" },
  { id: "Zeri", name: "Zeri", tags: ["Marksman"], title: "The Spark of Zaun" },
  { id: "Ziggs", name: "Ziggs", tags: ["Mage"], title: "the Hexplosives Expert" },
  { id: "Zilean", name: "Zilean", tags: ["Support", "Mage"], title: "the Chronokeeper" },
  { id: "Zoe", name: "Zoe", tags: ["Mage", "Support"], title: "the Aspect of Twilight" },
  { id: "Zyra", name: "Zyra", tags: ["Mage", "Support"], title: "Rise of the Thorns" }
];

// Search aliases for quick acronyms & easter eggs
const SEARCH_ALIASES = {
  "mf": "Miss Fortune",
  "gp": "Gangplank",
  "asol": "Aurelion Sol",
  "sol": "Aurelion Sol",
  "ww": "Warwick",
  "tk": "Tahm Kench",
  "tf": "Twisted Fate",
  "yi": "Master Yi",
  "mundo": "Dr. Mundo",
  "drmundo": "Dr. Mundo",
  "lb": "LeBlanc",
  "j4": "Jarvan IV",
  "noc": "Nocturne",
  "xin": "Xin Zhao",
  "kz": "Kha'Zix",
  "khazix": "Kha'Zix",
  "cho": "Cho'Gath",
  "chogath": "Cho'Gath",
  "kog": "Kog'Maw",
  "kogmaw": "Kog'Maw",
  "rek": "Rek'Sai",
  "reksai": "Rek'Sai",
  "nunu": "Nunu & Willump",
  "willump": "Nunu & Willump",
  "ksante": "K'Sante",
  "morde": "Mordekaiser",
  "renata": "Renata Glasc",
  "fiddle": "Fiddlesticks",
  "cass": "Cassiopeia",
  "cassio": "Cassiopeia",
  "heca": "Hecarim",
  "heimer": "Heimerdinger",
  "ez": "Ezreal",
  "blitz": "Blitzcrank",
  "ali": "Alistar",
  "eve": "Evelynn",
  "amumu": "Amumu",
  "trist": "Tristana",
  "trynd": "Tryndamere",
  "vlad": "Vladimir",
  "voli": "Volibear",
  // Easter egg searches
  "jason": "Annie",
  "phone": "Tryndamere",
  "phoneman": "Tryndamere",
  "dodo": ["Malphite", "Yuumi"]
};

// MetaSRC URL Slug Map
const METASRC_SLUG_MAP = {
  "Nunu & Willump": "nunu",
  "Jarvan IV": "jarvan",
  "K'Sante": "ksante",
  "Kai'Sa": "kaisa",
  "Kha'Zix": "khazix",
  "Cho'Gath": "chogath",
  "Vel'Koz": "velkoz",
  "Bel'Veth": "belveth",
  "Dr. Mundo": "dr-mundo",
  "Renata Glasc": "renata-glasc",
  "Wukong": "wukong",
  "LeBlanc": "leblanc",
  "Master Yi": "master-yi",
  "Miss Fortune": "miss-fortune",
  "Tahm Kench": "tahm-kench",
  "Twisted Fate": "twisted-fate",
  "Xin Zhao": "xin-zhao",
  "Aurelion Sol": "aurelion-sol"
};
